### ISSUE TITLE
Update repo secret

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/ipxedust#13]
This repo needs a GitHub API access token. That token is used to commit the iPXE binaries it builds. See this [doc](https://github.com/tinkerbell/boots-ipxe/blob/main/docs/IPXE.md) for more details on that.

Currently, the GitHub API access token is NOT from a shared account. It is from my account. We should ideally use a shared/robot account. Maybe the existing Tinkerbell org user: https://github.com/tinkerbot?

In the future I will be proposing we use [`goreleaser`](https://goreleaser.com/) and this also requires a GitHub access token.
https://goreleaser.com/ci/actions/?h=github

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by mmlb** [comment]
Hmm we don't we have a tinkerbell/ipxe repo that publishes github artifacts/releases and this repo fetches? Seems easier than having to track down if anything has changed/needs building. If not then yes we should use creds tied to the tinkerbot user imo.

**Comment by jacobweinstock** [comment]
I believe If we were to use _"github artifacts/releases and this repo fetches_", we would still have the challenge of committing iPXE binaries to the repo in an open and transparent way.

**Comment by mmlb** [comment]
Oh I wouldn't want to commit binaries to this repo either. The Makefile would fetch the binaries to the right spot from version urls and verifying checksums. Updates to this repo would still only occur via PRs and no new versions of iPXE could be introduced unless its bit-for-bit identical which ... not a problem? :D.

**Comment by jacobweinstock** [comment]
One of the [goals](https://github.com/tinkerbell/boots-ipxe#design-philosophy) of this repo is to be a Go library. See also, [proposal 0022](https://github.com/tinkerbell/proposals/tree/main/proposals/0022). Maybe there is a way, but I don't know how to make this a library without having the binaries checked in.

**Comment by mmlb** [comment]
Ah yeah thats a good point. I hadn't quite connected those dots. I'd only be worried about committing binaries to get and making the repo harder to use, but I don't think it'll be an issue in practice.

**Comment by jacobweinstock** [comment]
Update:

I'm looking into this idea:

https://github.com/martinbaillie/vault-plugin-secrets-github
https://www.youtube.com/watch?v=RDKeZiMaCf8

**Comment by nshalman** [comment]
I don't appear to have access to the repo settings. @mmlb do you have permissions to update the "Token" secret in this repo?

**Comment by mmlb** [comment]
@nshalman I do

**Comment by jacobweinstock** [comment]
> @jacobweinstock I've updated the token secret, its tied to tinkerbot user. How can we test it?
> 
> (says @mmlb)

looks like it worked here: https://github.com/tinkerbell/ipxedust/issues/13#issuecomment-1082373820

**Comment by mmlb** [comment]
Nice!
