### ISSUE TITLE
Do not modify the http object logger

### ISSUE THREAD

**Issue by rgl** [tinkerbell/ipxedust#15]
The following code seems to be reassigning the `s.Log` object at each request, which does not seem right. I think it should create a local `log` variable instead.

https://github.com/tinkerbell/boots-ipxe/blob/e9e36bd85356785cfeaf9e2f340d5a751f5b1708/http/http.go#L60

**Comment by jacobweinstock** [comment]
Hey @rgl. Good catch, thank you! I've updated PR #11 to address this.
